import Flutter
import UIKit
import DeviceCheck

@main
@objc class AppDelegate: FlutterAppDelegate, FlutterImplicitEngineDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  func didInitializeImplicitFlutterEngine(_ engineBridge: FlutterImplicitEngineBridge) {
    GeneratedPluginRegistrant.register(with: engineBridge.pluginRegistry)

    // ── Security channel (device_security) ──────────────────────────────────
    let secRegistrar = engineBridge.pluginRegistry.registrar(forPlugin: "SecurityPlugin")
    let secMessenger = secRegistrar?.messenger()
    if let secMessenger = secMessenger {
      let securityChannel = FlutterMethodChannel(
        name: "com.enagarsewa.app/device_security",
        binaryMessenger: secMessenger
      )
      securityChannel.setMethodCallHandler { call, result in
        switch call.method {
        case "isDeveloperModeEnabled":
          if #available(iOS 16.0, *) {
            result(DCDeveloperModeQuery.isEnabled)
          } else {
            result(false)
          }
        default:
          result(FlutterMethodNotImplemented)
        }
      }
    }

    let registrar = engineBridge.pluginRegistry.registrar(forPlugin: "IntegrityPlugin")
    let messenger = registrar?.messenger()
    guard let messenger = messenger else { return }

    let integrityChannel = FlutterMethodChannel(
      name: "com.enagarsewa.app/integrity",
      binaryMessenger: messenger
    )
    integrityChannel.setMethodCallHandler { [weak self] call, result in
      switch call.method {
      case "generateKey":
        self?.generateAttestKey(result: result)

      case "attestKey":
        guard let args = call.arguments as? [String: String],
              let keyId = args["keyId"],
              let clientDataHash = args["clientDataHash"] else {
          result(FlutterError(code: "INVALID_ARGS", message: "Missing keyId or clientDataHash", details: nil))
          return
        }
        self?.attestKey(keyId: keyId, clientDataHash: clientDataHash, result: result)

      case "generateAssertion":
        guard let args = call.arguments as? [String: String],
              let keyId = args["keyId"],
              let clientDataHash = args["clientDataHash"] else {
          result(FlutterError(code: "INVALID_ARGS", message: "Missing keyId or clientDataHash", details: nil))
          return
        }
        self?.generateAssertion(keyId: keyId, clientDataHash: clientDataHash, result: result)

      default:
        result(FlutterMethodNotImplemented)
      }
    }
  }

  // MARK: - App Attest

  /// Generates a new App Attest key in the Secure Enclave. Returns the key identifier.
  private func generateAttestKey(result: @escaping FlutterResult) {
    let service = DCAppAttestService.shared
    guard service.isSupported else {
      result(FlutterError(code: "NOT_SUPPORTED",
                          message: "App Attest is not supported on this device (requires iOS 14+ on real hardware)",
                          details: nil))
      return
    }
    service.generateKey { keyId, error in
      if let error = error {
        result(FlutterError(code: "KEY_GEN_ERROR", message: error.localizedDescription, details: nil))
      } else {
        result(keyId)
      }
    }
  }

  /**
   * Attests the key generated by generateAttestKey().
   * clientDataHash must be a standard Base64-encoded SHA-256 hash (32 bytes).
   * The returned attestation object (Base64) is sent to the backend for one-time verification.
   */
  private func attestKey(keyId: String, clientDataHash: String, result: @escaping FlutterResult) {
    let service = DCAppAttestService.shared
    guard service.isSupported else {
      result(FlutterError(code: "NOT_SUPPORTED", message: "App Attest not supported", details: nil))
      return
    }
    guard let hashData = Data(base64Encoded: clientDataHash), hashData.count == 32 else {
      result(FlutterError(code: "INVALID_HASH", message: "clientDataHash must be Base64-encoded SHA-256 (32 bytes)", details: nil))
      return
    }
    service.attestKey(keyId, clientDataHash: hashData) { attestation, error in
      if let error = error {
        result(FlutterError(code: "ATTEST_ERROR", message: error.localizedDescription, details: nil))
      } else if let attestation = attestation {
        result(attestation.base64EncodedString())
      } else {
        result(FlutterError(code: "ATTEST_ERROR", message: "No attestation data returned", details: nil))
      }
    }
  }

  /**
   * Generates an assertion for the given request data hash.
   * clientDataHash must be a standard Base64-encoded SHA-256 hash (32 bytes).
   * The returned assertion (Base64) is sent to the backend alongside each sensitive request.
   */
  private func generateAssertion(keyId: String, clientDataHash: String, result: @escaping FlutterResult) {
    let service = DCAppAttestService.shared
    guard service.isSupported else {
      result(FlutterError(code: "NOT_SUPPORTED", message: "App Attest not supported", details: nil))
      return
    }
    guard let hashData = Data(base64Encoded: clientDataHash), hashData.count == 32 else {
      result(FlutterError(code: "INVALID_HASH", message: "clientDataHash must be Base64-encoded SHA-256 (32 bytes)", details: nil))
      return
    }
    service.generateAssertion(keyId, clientDataHash: hashData) { assertion, error in
      if let error = error {
        result(FlutterError(code: "ASSERTION_ERROR", message: error.localizedDescription, details: nil))
      } else if let assertion = assertion {
        result(assertion.base64EncodedString())
      } else {
        result(FlutterError(code: "ASSERTION_ERROR", message: "No assertion data returned", details: nil))
      }
    }
  }
}

